-- 表領域の作成
CREATE TABLESPACE ZAIMU_DATA DATAFILE 'zaimu_data.dbf' SIZE 100M AUTOEXTEND ON;
CREATE TABLESPACE ZAIMU_INDEX DATAFILE 'zaimu_index.dbf' SIZE 50M AUTOEXTEND ON;

-- ユーザーテーブル
CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(10) NOT NULL CHECK (role IN ('teacher', 'student')),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (user_id)
) TABLESPACE ZAIMU_DATA;

-- 勘定科目マスタ
CREATE TABLE ACCOUNTS (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_name VARCHAR2(100) NOT NULL UNIQUE,
    account_type VARCHAR2(20) NOT NULL CHECK (account_type IN ('asset', 'liability', 'equity', 'revenue', 'expense')),
    PRIMARY KEY (account_id)
) TABLESPACE ZAIMU_DATA;

-- 取引テーブル
CREATE TABLE TRANSACTIONS (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    transaction_date DATE NOT NULL,
    description VARCHAR2(255),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (transaction_id),
    FOREIGN KEY (user_id) REFERENCES USERS(user_id)
) TABLESPACE ZAIMU_DATA;

-- 仕訳テーブル (取引の明細)
CREATE TABLE JOURNAL_ENTRIES (
    entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    transaction_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    debit_amount NUMBER(15, 2) DEFAULT 0,
    credit_amount NUMBER(15, 2) DEFAULT 0,
    PRIMARY KEY (entry_id),
    FOREIGN KEY (transaction_id) REFERENCES TRANSACTIONS(transaction_id),
    FOREIGN KEY (account_id) REFERENCES ACCOUNTS(account_id),
    CHECK (debit_amount >= 0 AND credit_amount >= 0 AND (debit_amount > 0 OR credit_amount > 0))
) TABLESPACE ZAIMU_DATA;

-- インデックスの作成
CREATE INDEX idx_users_username ON USERS(username) TABLESPACE ZAIMU_INDEX;
CREATE INDEX idx_transactions_user_id ON TRANSACTIONS(user_id) TABLESPACE ZAIMU_INDEX;
CREATE INDEX idx_journal_entries_transaction_id ON JOURNAL_ENTRIES(transaction_id) TABLESPACE ZAIMU_INDEX;
CREATE INDEX idx_journal_entries_account_id ON JOURNAL_ENTRIES(account_id) TABLESPACE ZAIMU_INDEX;

-- 初期勘定科目の挿入
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('現金', 'asset');
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('売掛金', 'asset');
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('商品', 'asset');
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('買掛金', 'liability');
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('借入金', 'liability');
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('資本金', 'equity');
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('売上', 'revenue');
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('仕入', 'expense');
INSERT INTO ACCOUNTS (account_name, account_type) VALUES ('給料', 'expense');

COMMIT;

